const products = [
  {
    name: "Green Leaf Lettuce",
    category: "popular",
    price: 14,
    id: 1,
    image: "./popular-products/Green-Leaf-Lettuce-each.webp",
    value: 0,
    quantity: 0,
    stock: 20,
  },
  {
    name: "Rainbow Chard",
    price: 13,
    id: 2,
    image: "./popular-products/Rainbow-Chard-Package-per-lb.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "popular",
  },
  {
    name: "Clementine",
    price: 13,
    id: 3,
    image: "./popular-products/Clementine-5ct.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "popular",
  },
  {
    name: "Kale Sprouts",
    price: 11,
    id: 4,
    image: "./popular-products/Kale-Sprouts-3oz.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "popular",
  },
  {
    name: "Rainbow Peppers",
    price: 15,
    id: 5,
    image: "./popular-products/Rainbow-Peppers-4ct.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "popular",
  },
  {
    name: "Blueberry",
    price: 11,
    id: 6,
    image: "./popular-products/Blackberries-1-25-qt.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "popular",
  },
  {
    name: "Calabaza Squash",
    price: 15,
    id: 7,
    image: "./popular-products/Calabaza-Squash-Package-each.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "popular",
  },
  {
    name: "Lettuce",
    price: 12,
    id: 8,
    image: "./popular-products/Lettuce-1lb.webp",
    value: 0,
    quantity: 0,
    category: "popular",
    stock: 20,
  },
  {
    name: "Radicchio",
    price: 14,
    id: 9,
    image: "./popular-products/Radicchio-12ct.webp",
    value: 0,
    quantity: 0,
    category: "popular",
    stock: 20,
  },
  {
    name: "Parsley",
    price: 13,
    id: 10,
    image: "./popular-products/Parsley-each.webp",
    value: 0,
    quantity: 0,
    category: "popular",
    stock: 20,
  },
  {
    name: "Strawberrie",
    price: 10,
    id: 11,
    image: "./popular-products/Strawberries-9-25oz.webp",
    value: 0,
    quantity: 0,
    category: "popular",
    stock: 20,
  },
  {
    name: "Purple Cauliflower",
    price: 15,
    id: 12,
    image: "./popular-products/Organic-Purple-Cauliflower-1lb.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "popular",
  },
  {
    name: "Organic Broccoli",
    price: 12,
    id: 13,
    image: "./popular-products/Organic-Broccoli-10oz.webp",
    value: 0,
    quantity: 0,
    category: "popular",
    stock: 20,
  },
];

export default products;
