const products = [
  {
    name: "Green Leaf Lettuce",
    category: "popular",
    price: 14,
    id: 1,
    image: "./popular-products/Green-Leaf-Lettuce-each.webp",
    value: 0,
    quantity: 0,
    stock: 20,
  },
  {
    name: "Rainbow Chard",
    price: 13,
    id: 2,
    image: "./popular-products/Rainbow-Chard-Package-per-lb.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "popular",
  },
  {
    name: "Clementine",
    price: 13,
    id: 3,
    image: "./popular-products/Clementine-5ct.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "popular",
  },
  {
    name: "Kale Sprouts",
    price: 11,
    id: 4,
    image: "./popular-products/Kale-Sprouts-3oz.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "popular",
  },
  {
    name: "Rainbow Peppers",
    price: 15,
    id: 5,
    image: "./popular-products/Rainbow-Peppers-4ct.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "popular",
  },
  {
    name: "Blueberry",
    price: 11,
    id: 6,
    image: "./popular-products/Blackberries-1-25-qt.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "popular",
  },
  {
    name: "Calabaza Squash",
    price: 15,
    id: 7,
    image: "./popular-products/Calabaza-Squash-Package-each.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "popular",
  },
  {
    name: "Lettuce",
    price: 12,
    id: 8,
    image: "./popular-products/Lettuce-1lb.webp",
    value: 0,
    quantity: 0,
    category: "popular",
    stock: 20,
  },
  {
    name: "Radicchio",
    price: 14,
    id: 9,
    image: "./popular-products/Radicchio-12ct.webp",
    value: 0,
    quantity: 0,
    category: "popular",
    stock: 20,
  },
  {
    name: "Parsley",
    price: 13,
    id: 10,
    image: "./popular-products/Parsley-each.webp",
    value: 0,
    quantity: 0,
    category: "popular",
    stock: 20,
  },
  {
    name: "Strawberrie",
    price: 10,
    id: 11,
    image: "./popular-products/Strawberries-9-25oz.webp",
    value: 0,
    quantity: 0,
    category: "popular",
    stock: 20,
  },
  {
    name: "Purple Cauliflower",
    price: 15,
    id: 12,
    image: "./popular-products/Organic-Purple-Cauliflower-1lb.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "popular",
  },
  {
    name: "Organic Broccoli",
    price: 12,
    id: 13,
    image: "./popular-products/Organic-Broccoli-10oz.webp",
    value: 0,
    quantity: 0,
    category: "popular",
    stock: 20,
  },

  {
    name: "Organic Bell Pepper",
    price: 14,
    prvPrice: 16,
    id: 14,
    off: 10,
    quantity: 0,
    category: "discount",
    stock: 20,
    image: "./discount-images/Orange-Bell-Pepper-22ct.webp",
  },
  {
    name: "Mini Pumpkin",
    price: 13,
    off: 8,
    prvPrice: 16,
    quantity: 0,
    category: "discount",
    stock: 10,
    id: 15,
    image: "./discount-images/Mini-Pumpkin-Box-each.webp",
  },
  {
    name: "Iglotex Cauliflower",
    price: 13,
    off: 12,
    prvPrice: 15,
    quantity: 0,
    category: "discount",
    stock: 25,
    id: 16,
    image: "./discount-images/Iglotex-Cauliflower-Florets.webp",
  },
  {
    name: "French Green Beans",
    price: 15,
    off: 10,
    prvPrice: 18,
    quantity: 0,
    category: "discount",
    stock: 20,
    id: 17,
    image: "./discount-images/French-Green-Beans-16ct.webp",
  },
  {
    name: "Escarole",
    price: 10,
    off: 15,
    prvPrice: 12,
    quantity: 0,
    category: "discount",
    stock: 20,
    id: 18,
    image: "./discount-images/Escarole-1ct.webp",
  },
  {
    name: "Haitian Mangoe",
    price: 8,
    off: 20,
    prvPrice: 10,
    quantity: 0,
    category: "discount",
    stock: 20,
    id: 19,
    image: "./discount-images/Haitian-Mango-8ct.webp",
  },
  {
    name: "Cranberries",
    price: 13,
    off: 12,
    prvPrice: 15,
    quantity: 0,
    category: "discount",
    stock: 20,
    id: 20,
    image: "./discount-images/Cranberries-Package-9-5-oz.webp",
  },
  {
    name: "Mandarin Clementine",
    price: 7,
    off: 15,
    prvPrice: 9,
    quantity: 0,
    category: "discount",
    stock: 20,
    id: 21,
    image: "./discount-images/Mandarin-Clementine-22lb.webp",
  },
];

export default products;
