const products = [
  {
    name: "Wild King Salmon",
    category: "sea-food",
    price: 14,
    id: 1,
    image: "./seafood-image/Fresh-Wild-King-Salmon-Steak-1lb.webp",
    value: 0,
    quantity: 0,
    stock: 20,
  },
  {
    name: "Canada Salmon",
    price: 13,
    id: 2,
    image: "./seafood-image/Fresh-Whole-Canada-Salmon-25-5-oz.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "sea-food",
  },
  {
    name: "Atlantic Salmon",
    price: 13,
    id: 3,
    image: "./seafood-image/Fresh-Whole-Atlantic-Salmon-Steaks-1lb.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "sea-food",
  },
  {
    name: "Salmon Filet Portion",
    price: 11,
    id: 4,
    image: "./seafood-image/Black-Pearls-Salmon-Filet-Portion-6-oz.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "sea-food",
  },
  {
    name: "Ling Cod Steak",
    price: 15,
    id: 5,
    image: "./seafood-image/Ling-Cod-Steak-1lb.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "sea-food",
  },
  {
    name: "Peeled Deveined",
    price: 11,
    id: 6,
    image: "./seafood-image/Cooked-Peeled-Deveined-Shrimp-2lb.webp",
    value: 0,
    quantity: 0,
    stock: 20,
    category: "sea-food",
  },
];

export default products;
